In [34]:
#Import the library
import pandas as pd
import numpy as np

In [35]:
#Read the CSV file into dataframe
df=pd.read_csv('stocks.csv')
df

,Ticker,Date,Open,High,Low,Close,Adj Close,Volume
0,AAPL,2023-02-07,150.639999,155.229996,150.639999,154.649994,154.414230,83322600
1,AAPL,2023-02-08,153.880005,154.580002,151.169998,151.919998,151.688400,64120100
2,AAPL,2023-02-09,153.779999,154.330002,150.419998,150.869995,150.639999,56007100
3,AAPL,2023-02-10,149.460007,151.339996,149.220001,151.009995,151.009995,57450700
4,AAPL,2023-02-13,150.949997,154.259995,150.919998,153.850006,153.850006,62199000
...,...,...,...,...,...,...,...,...
243,GOOG,2023-05-01,107.720001,108.680000,107.500000,107.709999,107.709999,20926300
244,GOOG,2023-05-02,107.660004,107.730003,104.500000,105.980003,105.980003,20343100
245,GOOG,2023-05-03,106.220001,108.129997,105.620003,106.120003,106.120003,17116300
246,GOOG,2023-05-04,106.160004,106.300003,104.699997,105.209999,105.209999,19780600
247,GOOG,2023-05-05,105.320000,106.440002,104.738998,106.214996,106.214996,20705300

In [36]:
# Check for missing values
df[['Ticker', 'Date', 'Close']].isnull().sum()

Ticker    0
Date      0
Close     0
dtype: int64

In [42]:
import numpy as np

# List of additional companies to include
additional_companies = ['TSLA', 'NFLX', 'FB', 'IBM', 'ORCL']

# Define typical price ranges for the new companies
price_ranges = {
    'AAPL': (120, 160),
    'GOOG': (1400, 1800),
    'MSFT': (200, 300),
    'AMZN': (3000, 3500),
    'TSLA': (600, 900),
    'NFLX': (300, 500),
    'FB': (250, 350),
    'IBM': (120, 150),
    'ORCL': (70, 100)
}

# Assuming df_pivot_reset is your original DataFrame

# Simulate stock prices for each company
for company, price_range in price_ranges.items():
    df_pivot_reset[company] = np.random.uniform(price_range[0], price_range[1], len(df_pivot_reset))

# Make a copy of the dataframe for further use
fd = df_pivot_reset.copy()

#Exclude the first column from calculations if it is not numeric
numeric_columns = fd.select_dtypes(include=np.number).columns
fd_numeric = fd[numeric_columns]

def identify_undervalued_stocks(data_frame,num_std_dev=2):
  # Calculate mean and standard deviation for numeric columns only
  mean_prices=data_frame.mean()
  std_dev_prices=data_frame.std()

  undervalued_stocks=[]
  for column in data_frame.columns:
    stock_std_dev=std_dev_prices[column]
    stock_mean=mean_prices[column]
    latest_price=data_frame[column].iloc[-1]
    if latest_price<(stock_mean-num_std_dev*stock_std_dev):
      undervalued_stocks.append(column)
  return undervalued_stocks

#Calling the function with the numeric dataframe
undervalued_stocks = identify_undervalued_stocks(fd_numeric,1)

if undervalued_stocks:
  print("Undervalued stocks:")
  for stock in undervalued_stocks:
    print(stock)
else:
  print("No undervalued stocks found.")

print(undervalued_stocks)

Undervalued stocks:
AAPL
MSFT
NFLX
FB
['AAPL', 'MSFT', 'NFLX', 'FB']

In [43]:
fd

,Date,AAPL,GOOG,MSFT,NFLX,AMZN,TSLA,FB,IBM,ORCL
0,2023-02-07,152.315818,1645.422062,268.059803,350.889318,3218.552604,739.258695,292.314659,146.887890,89.480080
1,2023-02-08,145.202974,1788.423079,279.379257,340.998797,3220.658995,730.214551,329.027069,147.126503,74.886848
2,2023-02-09,158.323754,1577.017592,239.459641,486.653962,3066.049986,657.290858,341.401233,133.402723,71.816001
3,2023-02-10,147.583805,1589.660435,231.786486,442.715729,3248.384220,757.674765,318.973949,121.570050,73.744189
4,2023-02-13,129.231609,1572.035192,208.783544,410.845381,3416.717305,829.953501,256.011228,127.214209,72.058099
...,...,...,...,...,...,...,...,...,...,...
57,2023-05-01,123.774086,1654.988918,200.815267,371.747759,3117.496822,798.068671,341.912602,140.970515,82.865566
58,2023-05-02,151.294136,1458.277122,236.235225,343.981659,3120.518774,699.736359,319.511329,141.680622,88.385931
59,2023-05-03,144.084737,1530.974694,253.176607,485.522629,3182.599981,879.561649,251.563962,137.946257,91.047430
60,2023-05-04,127.815359,1555.848337,229.082860,331.251574,3060.237405,679.232429,268.944105,122.460144,82.263114
61,2023-05-05,127.231066,1522.955321,216.228194,320.395455,3126.065746,851.129480,264.328337,137.642991,82.217987